### ISSUE TITLE
Missing gists

### ISSUE THREAD

**Issue by vladkolodka** [aspnet/Docs.ru-ru#25]
В файле по ссылке отсутствуют вставки с текстами програм.
https://github.com/aspnet/Docs.ru-ru/blob/live/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity.md

**Comment by LisandroSu** [comment]
Здравствуйте, @vladkolodka ! 

Спасибо за отзыв. 

Мы активно просматриваем комментарии и скоро ответим Вам. 

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Issue moved to [aspnet/Docs #8229](https://github.com/aspnet/Docs/issues/8229) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @vladkolodka! 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/aspnet/Docs/issues/8229. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
