### ISSUE TITLE
Ссылки на статьи не соответствуют названию заголовков

### ISSUE THREAD

**Issue by SovRedBit** [aspnet/Docs.ru-ru#40]
При просмотре документации на русском языке я замечаю что в каждом подразделе в дереве разделов который находится с левой стороны в первом пункте написано **"Обзор набора средств Visual Studio для Unity"** хотя в самой статье заголовок **"Предотвращения межсайтовых (запросов XSRF/CSRF) атак с подделкой в ASP.NET Core"** такую проблему я наблюдаю только на Русском, на английском языке такой проблемы я не вижу.

**Comment by CeciAc** [comment]
Здравствуйте, @SovRedBit 
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @SovRedBit 
 Благодарим за Ваши лингвистические правки.  
К сожалению, рассмотрев Ваш отзыв, наши лингвисты не смогли принять его, так как он не соответствует в полной мере нашим критериям по следующим причинам: [Мы проверили страницу (https://docs.microsoft.com/ru-ru/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1) и не обнаружили там описанной проблемы. Заголовок с правой стороны "Обзор набора средств Visual Studio для Unity" — заголовок верхнего уровня. Если открыть статью "Предотвращения межсайтовых (запросов XSRF/CSRF) атак с подделкой в ASP.NET Core", слева будет выделен соответствующий ей заголовок "Защита от подделки запросов"] 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by SovRedBit** [comment]
Это конечно прекрасно, что они не смогли найти, но это не обозначает что проблемы нету, давайте я покажу вам скриншот 
![0587c5ca-216b-4ea6-9e5b-82ff2547343e](https://user-images.githubusercontent.com/23471273/49664273-70bd6700-fa62-11e8-8e20-ea2cd8a25c12.jpeg)

**Comment by SovRedBit** [comment]
Так что переоткройте пожалуйста эту тему. Во многих местах эта ошибка.

**Comment by CeciAc** [comment]
Здравствуйте, @SovRedBit
Спасибо за отзыв.
Мы активно просматриваем комментарии и скоро ответим Вам.
С наилучшими пожеланиями,
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @SovRedBit 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1.  
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by SovRedBit** [comment]
Спасибо пока этой ошибки больше не наблюдаю!
